<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <h1><?php _e('Holiday list'); ?></h1>
    <?php if (!empty($holidayList)) { ?>
        <table class="table table-striped table-bordered table-hover table-sm mt-3 mb-3">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Date'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($holidayList as $holiday) { ?>
                <tr>
                    <td><?php echo $this->escape($holiday['id']); ?></td>
                    <td><?php echo $this->escape($holiday['date_view']); ?></td>
                    <td>
                        <a class="btn btn-primary btn-sm" title="<?php _e('Edit'); ?>"
                           href="<?php echo $this->url('', ['action' => 'update', 'id' => $holiday['id']]); ?>">
                            <i class="far fa-eye"></i> <?php _e('Edit'); ?>
                        </a>
                    </td>
                </tr>
            <?php } ?>
        </table>
        <div class="paginator mt-3 mb-3">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator'); ?>
        </div>
    <?php } else { ?>
        <div class="alert alert-danger mt-3 mb-3">
            <?php _e('No holiday added yet !'); ?>
        </div>
    <?php } ?>
</div>