<?php
$this->css(
    [
        pi::url('static/vendor/select2/css/select2.css'),
        $this->assetModule('css/admin.css'),
    ]
);
$this->jQuery();
$this->js(
    [
        pi::url('static/vendor/select2/js/select2.full.js'),
    ]
);

// Set page script
$script = <<<'EOT'
    (function ($) {
        $(document).ready(function () {
            $('.chosen-select').select2();
        });

        $(document).ready(function ($) {
            $('.date-list').change(function () {
                let date = $('.date-list').val();
                let provider = $('.provider-list').val();
                let service = $('.service-list').val();
                let url = '%s/date/' + date + '/provider/' + provider + '/service/' + service;
                console.log(url);
                $.getJSON(url).done(function (result) {
                    $('.hour-list').html('');
                    if (result.result == true) {
                        $.each(result.data, function (key, value) {
                            $('.hour-list').append(new Option(value, key));
                        });
                    } else {
                        let html = '<div class="alert alert-danger">' + result.error.message + '</div>';
                        $('.hour-list').append(html);
                    }
                });
            });
        });
    })(jQuery)
EOT;
$script = sprintf(
    $script,
    $hourUrl
);
$this->footScript()->appendScript($script);
?>
<div class="clearfix">
    <h1><?php _e('Add / edit schedule'); ?></h1>
    <?php echo $this->form($form); ?>
</div>
