<?php
$this->css(
    [
        pi::url('static/vendor/select2/css/select2.css'),
        $this->assetModule('css/admin.css'),
    ]
);
$this->jQuery();
$this->js(
    [
        pi::url('static/vendor/select2/js/select2.full.js'),
    ]
);
?>
<div class="clearfix">
    <h1><?php _e('Add / edit schedule'); ?></h1>
    <?php echo $this->form($form); ?>
</div>
<script>
    $(document).ready(function () {
        $('.chosen-select').select2();
    });
</script>