<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <h1><?php _e('Service list'); ?></h1>
    <?php if (!empty($serviceList)) { ?>
    <table class="table table-striped table-bordered table-hover table-sm mt-3 mb-3">
        <tr>
            <th><?php _e('ID'); ?></th>
            <th><?php _e('Title'); ?></th>
            <th><?php _e('Amount'); ?></th>
            <th><?php _e('Status'); ?></th>
            <th><?php _e('Action'); ?></th>
        </tr>
        <?php foreach ($serviceList as $service) { ?>
            <?php if ($service['status'] == 1) {
                $badgeIdClass = 'badge-success';
            } else {
                $badgeIdClass = 'badge-warning';
            } ?>
            <tr>
                <td>
                    <span class="badge <?php echo $badgeIdClass; ?>">
                        <?php echo $this->escape($service['id']); ?>
                    </span>
                </td>
                <td><?php echo $this->escape($service['title']); ?></td>
                <td><?php echo $this->escape($service['amount_view']); ?></td>
                <td><?php echo $this->escape($service['status_view']); ?></td>
                <td>
                    <a class="btn btn-primary btn-sm" title="<?php _e('Edit'); ?>"
                       href="<?php echo $this->url('', ['action' => 'update', 'id' => $service['id']]); ?>">
                        <i class="fa fa-edit"></i> <?php _e('Edit'); ?>
                    </a>
                </td>
            </tr>
        <?php } ?>
    </table>
    <?php } else {?>
        <div class="alert alert-danger mt-3 mb-3">
            <?php _e('Please add service !'); ?>
        </div>
    <?php } ?>
</div>