<?php
$this->css(
    [
        $this->assetModule('css/front.css'),
        $this->assetModule('script/system-ui.css', 'system'),
    ]
);
$this->jQuery();
$this->backbone();
$this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<div id="js-list" class="clearfix">
    <div class="row clearfix">
        <div class="col-lg-6 col-md-6 col-6 mt-3 mb-3">
            <h1><?php _e('Reservation list'); ?></h1>
        </div>
        <div class="col-lg-6 col-md-6 col-6 mt-3 mb-3">
            <a class="btn btn-primary btn-sm float-right" href="<?php echo $this->url('', ['controller' => 'update', 'action' => 'index']); ?>">
                <i class="fa fa-plus"></i> <?php _e('New reservation'); ?>
            </a>
        </div>
    </div>
    <?php if (isset($scheduleList['list']) && !empty($scheduleList['list'])) { ?>
        <?php foreach ($scheduleList['list'] as $scheduleSingle) { ?>
            <div class="card <?php //echo $scheduleSingle['card_class']; ?> mb-4" id="schedule-<?php echo $this->escape($scheduleSingle['id']); ?>" data-cancel="<?php echo $this->escape($scheduleSingle['urlCancel']); ?>">
                <div class="card-body">
                    <h5 class="card-title"><?php echo $this->escape($scheduleSingle['title']); ?></h5>
                    <div class="card-text">
                        <div class="row clearfix">
                            <div class="col-lg-3 col-md-3 col-12">
                                <ul class="list-inline mb-3">
                                    <li class="list-inline-item"><?php _e('Provider'); ?> : <strong><?php echo $this->escape($scheduleSingle['provider_title']); ?></strong></li>
                                    <li class="list-inline-item"><?php _e('Service'); ?> : <strong><?php echo $this->escape($scheduleSingle['service_title']); ?></strong></li>
                                </ul>
                            </div>
                            <div class="col-lg-3 col-md-3 col-12">
                                <ul class="list-inline mb-3">
                                    <li class="list-inline-item"><?php _e('Date'); ?> : <strong><?php echo $this->escape($scheduleSingle['reserve_date_view']); ?></strong></li>
                                    <li class="list-inline-item"><?php _e('From'); ?> : <strong><?php echo $this->escape($scheduleSingle['reserve_from']); ?></strong></li>
                                    <li class="list-inline-item"><?php _e('To'); ?> : <strong><?php echo $this->escape($scheduleSingle['reserve_to']); ?></strong></li>
                                </ul>
                            </div>
                            <div class="col-lg-4 col-md-4 col-12">
                                <ul class="list-inline mb-3">
                                    <li class="list-inline-item"><?php _e('Payment'); ?> : <strong class="schedule-payment"><?php echo $this->escape($scheduleSingle['payment_status_view']); ?></strong></li>
                                    <li class="list-inline-item"><?php _e('Reserve'); ?> : <strong class="schedule-reserve"><?php echo $this->escape($scheduleSingle['reserve_status_view']); ?></strong></li>
                                </ul>
                            </div>
                            <div class="col-lg-2 col-md-2 col-12">
                                <ul class="list-inline mb-3 float-right">
                                    <li class="list-inline-item">
                                        <a class="btn btn-primary btn-sm" title="<?php _e('View'); ?>"
                                           href="<?php echo $this->url('', ['controller' => 'view', 'action' => 'index', 'id' => $scheduleSingle['id']]); ?>">
                                            <i class="fa fa-eye"></i> <?php _e('View'); ?>
                                        </a>
                                    </li>
                                    <?php if ($scheduleSingle['cancel_user']) { ?>
                                        <li class="list-inline-item">
                                            <button class="schedule-cancel btn btn-warning btn-sm">
                                                <i class="fa fa-eye"></i> <?php _e('Cancel'); ?>
                                            </button>
                                        </li>
                                    <?php } ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php } ?>
    <?php } else { ?>
        <div class="alert alert-danger mt-3 mb-3">
            <?php _e('You still not send any reserve request yet !'); ?>
        </div>
    <?php } ?>
</div>
<script>
    (function ($) {
        var page = {
            el: $('#js-list'),
            modal: $('<div class="modal fade">').appendTo(document.body),
            $: function (selector) {
                return this.el.find(selector);
            },
            init: function () {
                _.bindAll(this);
                this.$('.schedule-cancel').click(this.scheduleCancelAction);
            },
            scheduleCancelAction: function (e) {
                var p = $(e.target).parents('div.card'),
                    self = this;
                if (confirm("<?php _e('Aye you sure you want cancel this schedule ?'); ?>")) {
                    systemMessage.wait("<?php _e('Cancel in process'); ?>");
                    $.getJSON(p.attr("data-cancel")).done(function (result) {
                        if (result.result) {
                            $('#schedule-' + result.data.id + ' .schedule-cancel').remove();
                            $('#schedule-' + result.data.id + ' .schedule-reserve').html(result.data.text);
                            systemMessage.succ(result.data.message);
                        } else {
                            systemMessage.fail(result.data.message);
                        }
                    });
                }
            },
        }
        page.init();
    })(jQuery)
</script>
