<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix">
    <div class="row clearfix">
        <div class="col-lg-6 col-md-6 col-6 mt-3 mb-3">
            <h1><?php _e('List of reservation'); ?></h1>
        </div>
        <div class="col-lg-6 col-md-6 col-6 mt-3 mb-3">
            <a class="btn btn-primary btn-sm text-right pull-right" href="<?php echo $this->url('', ['controller' => 'update', 'action' => 'index']); ?>">
                <i class="fa fa-plus"></i> <?php _e('Make new reservation'); ?>
            </a>
        </div>
    </div>
    <?php if (isset($scheduleList['list']) && !empty($scheduleList['list'])) { ?>
        <table class="table table-striped table-bordered table-hover table-sm mt-3 mb-3">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Time'); ?></th>
                <th><?php _e('Amount'); ?></th>
                <th><?php _e('Provider'); ?></th>
                <th><?php _e('Status'); ?></th>
                <?php /*<th><?php _e('Action'); ?></th> */ ?>
            </tr>
            <?php foreach ($scheduleList['list'] as $scheduleSingle) { ?>
                <tr>
                    <td><?php echo $this->escape($scheduleSingle['id']); ?></td>
                    <td>
                        <ul class="list-unstyled">
                            <li><?php _e('Date'); ?> : <strong><?php echo $this->escape($scheduleSingle['reserve_date_view']); ?></strong></li>
                            <li><?php _e('From'); ?> : <strong><?php echo $this->escape($scheduleSingle['reserve_from']); ?></strong></li>
                            <li><?php _e('To'); ?> : <strong><?php echo $this->escape($scheduleSingle['reserve_to']); ?></strong></li>
                        </ul>
                    </td>
                    <td><?php echo $this->escape($scheduleSingle['amount_view']); ?></td>
                    <td><?php echo $this->escape($scheduleSingle['provider_title']); ?></td>
                    <td>
                        <ul class="list-unstyled">
                            <li><?php _e('Payment'); ?> : <strong><?php echo $this->escape($scheduleSingle['payment_status_view']); ?></strong></li>
                            <li><?php _e('Reserve'); ?> : <strong><?php echo $this->escape($scheduleSingle['reserve_status_view']); ?></strong></li>
                        </ul>
                    </td>
                    <?php /* <td>
                        <a class="btn btn-primary btn-sm" title="<?php _e('Edit'); ?>"
                           href="<?php echo $this->url('', ['controller' => 'view', 'action' => 'index', 'id' => $scheduleSingle['id']]); ?>">
                            <i class="fa fa-eye"></i> <?php _e('View'); ?>
                        </a>
                    </td> */ ?>
                </tr>
            <?php } ?>
        </table>
    <?php } else { ?>
        <div class="alert alert-danger mt-3 mb-3">
            <?php _e('You still not send any reserve request yet !'); ?>
        </div>
    <?php } ?>
</div>