<?php
$this->css(
    [
        pi::url('static/vendor/select2/css/select2.css'),
        $this->assetModule('css/front.css'),
    ]
);
$this->jQuery();
$this->js(
    [
        pi::url('static/vendor/select2/js/select2.full.js'),
    ]
);

// Set page script
$script = <<<'EOT'
    (function ($) {
        $(document).ready(function () {
            $('.chosen-select').select2();
        });

        $(document).ready(function ($) {
            $('.date-list').change(function () {
                let date = $('.date-list').val();
                let provider = $('.provider-list').val();
                let service = $('.service-list').val();
                let url = '%s/date/' + date + '/provider/' + provider + '/service/' + service;
                console.log(url);
                $.getJSON(url).done(function (result) {
                    $('.hour-list').html('');
                    if (result.result == true) {
                        $.each(result.data, function (key, value) {
                            let html = '<div class="event_item">' +
                                '<div class="form-check">\n' +
                                '<input class="form-check-input" type="radio" name="reserve_from" value="' + value + '" id="hour-' + key + '">\n' +
                                '<label class="form-check-label" for="hour-' + key + '">\n' +
                                '<div class="ei_Title">' + value + '</div>\n' +
                                '</label>\n' +
                                '</div>' +
                                '</div>';
                            $('.hour-list').append(html);
                        });
                    } else {
                        let html = '<div class="alert alert-danger">' + result.error.message + '</div>';
                        $('.hour-list').append(html);
                    }
                });
            });
        });
    })(jQuery)
EOT;
$script = sprintf(
    $script,
    $hourUrl
);
$this->footScript()->appendScript($script);
?>
<div class="clearfix">
    <div class="calendar dark">
        <div class="calendar_header">
            <h1 class="header_title"><?php _e('Welcome back'); ?></h1>
            <p class="header_copy"><?php _e('Please select your day and hour for reserve schedule'); ?></p>
        </div>
        <div class="calendar_plan">
            <div class="cl_plan">
                <div class="cl_title"><?php _e('Today'); ?></div>
                <div class="cl_copy"><?php echo _date(time(), ['format' => 'l j F Y']) ?></div>
            </div>
        </div>
        <div class="calendar_events">
            <?php echo $this->form($form, 'vertical'); ?>
        </div>
    </div>
</div>