<?php
$this->css(
    [
        $this->assetModule('css/front.css'),
        $this->assetModule('script/system-ui.css', 'system'),
    ]
);
$this->jQuery();
$this->backbone();
$this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<div id="js-list" class="clearfix">
    <div class="row">
        <div class="col-lg-6 col-md-6 col-12 justify-content-center">
            <h1><?php _e('Reservation details'); ?></h1>
            <div class="card <?php //echo $schedule['card_class']; ?> mb-4" id="schedule-<?php echo $this->escape($schedule['id']); ?>" data-cancel="<?php echo $this->escape($schedule['urlCancel']); ?>">
                <div class="card-body">
                    <h5 class="card-title"><?php echo $this->escape($schedule['title']); ?></h5>
                    <div class="card-text">
                        <div class="row clearfix">
                            <div class="col-lg-3 col-md-3 col-12">
                                <ul class="list-inline mb-3">
                                    <li class="list-inline-item"><?php _e('Provider'); ?> : <strong><?php echo $this->escape($schedule['provider_title']); ?></strong></li>
                                    <li class="list-inline-item"><?php _e('Service'); ?> : <strong><?php echo $this->escape($schedule['service_title']); ?></strong></li>
                                </ul>
                            </div>
                            <div class="col-lg-3 col-md-3 col-12">
                                <ul class="list-inline mb-3">
                                    <li class="list-inline-item"><?php _e('Date'); ?> : <strong><?php echo $this->escape($schedule['reserve_date_view']); ?></strong></li>
                                    <li class="list-inline-item"><?php _e('From'); ?> : <strong><?php echo $this->escape($schedule['reserve_from']); ?></strong></li>
                                    <li class="list-inline-item"><?php _e('To'); ?> : <strong><?php echo $this->escape($schedule['reserve_to']); ?></strong></li>
                                </ul>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-4 col-md-4 col-12">
                                <ul class="list-inline mb-3">
                                    <li class="list-inline-item"><?php _e('Payment'); ?> : <strong class="schedule-payment"><span class="<?php echo $schedule['payment_class']; ?>"><?php echo $this->escape($schedule['payment_status_view']); ?></span></strong></li>
                                    <li class="list-inline-item"><?php _e('Reserve'); ?> : <strong class="schedule-reserve"><span class="<?php echo $schedule['reserve_class']; ?>"><?php echo $this->escape($schedule['reserve_status_view']); ?></span></strong></li>
                                </ul>
                            </div>
                            <div class="col-lg-2 col-md-2 col-12">
                                <ul class="list-inline mb-3 float-right">
                                    <?php if ($schedule['cancel_user']) { ?>
                                        <li class="list-inline-item">
                                            <button class="schedule-cancel btn btn-warning btn-sm">
                                                <i class="fa fa-eye"></i> <?php _e('Cancel'); ?>
                                            </button>
                                        </li>
                                    <?php } ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-12 justify-content-center">
            <div class="calendar light mb-3 mt-3">
                <div class="calendar_header">
                    <h1 class="header_title d-none d-sm-block"><?php _e('Notes'); ?></h1>
                    <p class="header_copy"><?php _e('Reservation roles and information!'); ?></p>
                </div>
                <div class="calendar_plan">
                    <div class="cl_plan">
                        <div class="cl_title"><?php _e('Today'); ?></div>
                        <div class="cl_copy"><?php echo _date(time(), ['format' => 'l j F Y']) ?></div>
                    </div>
                </div>
                <div class="calendar_events">
                    <ul class="list-unstyled">
                        <li class="mt-2 mb-3"><strong>1-</strong> Make sure select true time and service, Make sure select true time and service, Make sure select true time and service</li>
                        <li class="mt-2 mb-3"><strong>2-</strong> Make sure select true time and service, Make sure select true time and service, Make sure select true time and service, Make sure select true time and service</li>
                        <li class="mt-2 mb-3"><strong>3-</strong> Make sure select true time and service, Make sure select true time and service, Make sure select true time and service</li>
                        <li class="mt-2 mb-3"><strong>4-</strong> Make sure select true time and service, Make sure select true time and service, Make sure select true time and service</li>
                        <li class="mt-2 mb-3"><strong>5-</strong> Make sure select true time and service, Make sure select true time and service, Make sure select true time and service, Make sure select true time and service</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    (function ($) {
        var page = {
            el: $('#js-list'),
            modal: $('<div class="modal fade">').appendTo(document.body),
            $: function (selector) {
                return this.el.find(selector);
            },
            init: function () {
                _.bindAll(this);
                this.$('.schedule-cancel').click(this.scheduleCancelAction);
            },
            scheduleCancelAction: function (e) {
                var p = $(e.target).parents('div.card'),
                    self = this;
                if (confirm("<?php _e('Aye you sure you want cancel this schedule ?'); ?>")) {
                    systemMessage.wait("<?php _e('Cancel in process'); ?>");
                    $.getJSON(p.attr("data-cancel")).done(function (result) {
                        if (result.result) {
                            $('#schedule-' + result.data.id + ' .schedule-cancel').remove();
                            $('#schedule-' + result.data.id + ' .schedule-reserve').html('<span class="' + result.data.css + '">' + result.data.text + '</span>');
                            systemMessage.succ(result.data.message);
                        } else {
                            systemMessage.fail(result.data.message);
                        }
                    });
                }
            },
        }
        page.init();
    })(jQuery)
</script>
